name: iOS
on:
  pull_request:
    paths:
      - 'package/ios/**'
      - 'package/cpp/**'
      - 'package/example/package.json'
      - '.github/workflows/**'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14
    env:
      TURBO_CACHE_DIR: package/.turbo/ios
    strategy:
      matrix:
        working-directory: [package/example]
    concurrency:
      group: ios-example-${{ matrix.working-directory }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          cache-dependency-path: package/yarn.lock

      - name: Install Package
        run: cd package; yarn install --immutable

      - name: Download Dawn Binary Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: "build-dawn.yml"
          repo: wcandillon/react-native-webgpu
          github_token: ${{secrets.GITHUB_TOKEN}}
          path: artifacts
          branch: main
          name: dawn-libs

      - name: Copy Artifacts to libs folder
        working-directory: package
        run: yarn copy-artifacts

      - name: Cache turborepo for iOS
        uses: actions/cache@v3
        with:
          path: ${{ env.TURBO_CACHE_DIR }}
          key: ${{ runner.os }}-turborepo-ios-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-turborepo-ios-

      - name: Check turborepo cache for iOS
        working-directory: package
        run: |
          TURBO_CACHE_STATUS=$(node -p "($(yarn turbo run build:ios --cache-dir="${{ env.TURBO_CACHE_DIR }}" --dry=json)).tasks.find(t => t.task === 'build:ios').cache.status")

          if [[ $TURBO_CACHE_STATUS == "HIT" ]]; then
            echo "turbo_cache_hit=1" >> $GITHUB_ENV
          fi

      - name: Cache cocoapods
        if: env.turbo_cache_hit != 1
        id: cocoapods-cache
        uses: actions/cache@v3
        with:
          path: |
            **/ios/Pods
          key: ${{ runner.os }}-cocoapods-${{ hashFiles('package/example/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-cocoapods-

      - name: Install cocoapods
        if: env.turbo_cache_hit != 1 && steps.cocoapods-cache.outputs.cache-hit != 'true'
        working-directory: package
        run: |
          cd example/ios
          pod install
        env:
          NO_FLIPPER: 1

      - name: Build example for iOS
        working-directory: package
        run: |
          yarn turbo run build:ios --cache-dir="${{ env.TURBO_CACHE_DIR }}"

      # - name: Run e2e tests
      #   working-directory: package
      #   run: yarn e2e

      # - name: Start package manager
      #   working-directory: example
      #   run: E2E=true yarn start &

      # - name: Take screenshot
      #   run: xcrun simctl io booted screenshot screenshot.png
        
      # - uses: actions/upload-artifact@v2
      #   with:
      #     path: screenshot.png
      #     name: Download-screenshots
