name: Build Dawn
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r22b

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - name: Install Package
        run: cd package; yarn install --frozen-lockfile

      - name: Build Dawn
        working-directory: package
        env:
          ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: yarn build-dawn

      - name: Upload artifacts - Dawn Library Files
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: dawn-libs
          path: |
            package/libs
            package/cpp/dawn
            package/cpp/webgpu
