name: Build Dawn
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-latest
    env:
      WORKING_DIRECTORY: ./package
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r22b

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup Nodejs and npm
        uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: Install root node dependencies
        run: yarn

      - name: Build Dawn
        working-directory: ${{ env.WORKING_DIRECTORY }}/
        env:
          ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: yarn build-dawn

      - name: Upload artifacts - Dawn Library Files
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: dawn-libs
          path: |
            ${{ env.WORKING_DIRECTORY }}/libs
            ${{ env.WORKING_DIRECTORY }}/cpp/dawn
            ${{ env.WORKING_DIRECTORY }}/cpp/webgpu
